apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: diziano/gitops
  newTag: d5ad5asd56as6a
- name: nodeserver
  newName: diziano/gitops
  newTag: 9c39238c23659e326acabc5fcd10e71a4a2e5038
